const ShopAcTionTypes = {
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE'

}

export default ShopAcTionTypes;